"""initial migration

Revision ID: 395ac0c52cef
Revises: 
Create Date: 2025-09-21 15:13:12.908633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395ac0c52cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('FIAT', 'CRYPTO', 'METAL', name='currencytypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_type'], ['currency_type.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate')
    op.drop_table('asset')
    op.drop_table('currency')
    op.drop_table('user')
    op.drop_table('currency_type')
    # ### end Alembic commands ###
